// TokenTrim Phase 6 — Runtime Invariant Firewall (Deterministic, zero-dependency).
//
// Solves "Yes Man Scope Creep" and "Context Amnesia":
//   1. Extracts Hard Invariants (prohibitions & boundaries) from user input.
//   2. Injects a concise immutable boundary contract into downstream agent prompts.
//   3. Inspects agent outputs/tool actions for invariant violations.

import os from "node:os";
import path from "node:path";
import { extractRequirements, phraseKey, SpecLedger } from "./ledger.js";

/**
 * Format active prohibitions into a concise contract section for downstream agents.
 *
 * @param {Array<Object>} requirements Array from extractRequirements
 * @returns {string|null} Markdown block or null if no prohibitions found
 */
export function formatBoundaryContract(requirements) {
  if (!Array.isArray(requirements) || requirements.length === 0) return null;
  const prohibitions = requirements.filter((r) => r.kind === "prohibition");
  if (prohibitions.length === 0) return null;

  const lines = [
    "## Hard Boundaries & Invariants (DO NOT VIOLATE)",
    "The user has explicitly placed the following items OUT OF SCOPE. Do not implement, scaffold, or suggest them:",
  ];

  for (const p of prohibitions) {
    lines.push(`- PROHIBITED [${p.key}]: "${p.phrase}"`);
  }

  return lines.join("\n");
}

/**
 * Audit an agent response or tool call payload against active prohibitions.
 *
 * @param {string} agentText Text generated by the agent or tool call args
 * @param {Array<Object>} activeProhibitions List of active prohibitions
 * @returns {{ clean: boolean, violations: Array<Object>, warning: string|null }}
 */
export function auditAgentOutput(agentText, activeProhibitions) {
  if (!agentText || !Array.isArray(activeProhibitions) || activeProhibitions.length === 0) {
    return { clean: true, violations: [], warning: null };
  }

  const text = String(agentText).toLowerCase();
  const violations = [];

  for (const p of activeProhibitions) {
    // Check if the agent is actively implementing or adding the prohibited feature
    const key = p.key.toLowerCase();
    // Action verbs paired with prohibited keys (e.g. "adding auth", "installed passport", "create login")
    const actionRegex = new RegExp(`\\b(?:add|adds|added|adding|implement|implements|implemented|implementing|install|installed|installing|create|creates|created|creating|configure|configured|configuring)\\s+(?:[\\w-]+\\s+){0,3}${key}\\b`, "i");
    // Direct mention in code imports or dependencies (e.g. "jsonwebtoken", "passport", "bcrypt" for auth)
    const codeRegex = key === "auth"
      ? /\b(?:passport|jsonwebtoken|jwt|bcrypt|next-auth|lucia-auth)\b/i
      : null;

    if (actionRegex.test(text) || (codeRegex && codeRegex.test(text))) {
      violations.push({
        prohibition: p,
        detectedKey: key,
        reason: `Agent attempted action involving prohibited feature "${p.key}" (from: "${p.phrase}")`,
      });
    }
  }

  if (violations.length > 0) {
    const warning = `[INVARIANT FIREWALL WARNING] Agent activity violated ${violations.length} hard boundary: ` +
      violations.map((v) => `PROHIBITED: ${v.detectedKey}`).join(", ");
    return { clean: false, violations, warning };
  }

  return { clean: true, violations: [], warning: null };
}

/**
 * Session firewall manager combining ledger tracking and real-time output auditing.
 */
export class SessionFirewall {
  constructor(ledgerOrPath = null) {
    if (ledgerOrPath instanceof SpecLedger) {
      this.ledger = ledgerOrPath;
    } else {
      const p = typeof ledgerOrPath === "string"
        ? ledgerOrPath
        : path.join(os.tmpdir(), `tokentrim-fw-${Date.now()}-${Math.random().toString(36).slice(2)}.json`);
      this.ledger = new SpecLedger(p);
    }
  }

  /**
   * Process a user message: updates ledger and returns extracted invariants.
   */
  processUserMessage(text) {
    const res = this.ledger.processMessage(text, { trusted: true });
    const requirements = extractRequirements(text);
    const contract = formatBoundaryContract(requirements);
    return {
      ledgerResult: res,
      requirements,
      contract,
      activeProhibitions: this.ledger.activeEntries().filter((e) => e.kind === "prohibition"),
    };
  }

  /**
   * Audit an agent turn against active session prohibitions.
   */
  auditResponse(agentText) {
    const activeProhibitions = this.ledger.activeEntries().filter((e) => e.kind === "prohibition");
    return auditAgentOutput(agentText, activeProhibitions);
  }
}
